-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "desc:Sharp Corporation 0x149A", mode = "1920x1080@59.999", position = "0x0", scale = 1, vrr = 0 })
hl.monitor({ output = "desc:Dell Inc. DELL P2425H 2RHZH14", mode = "1920x1080@100.000", position = "1920x0", scale = 1, vrr = 0 })
