#!/bin/bash
# Add color support to various commands
alias grep="ugrep --color=auto"
alias fgrep="ugrep -F --color=auto"
alias egrep="ugrep -E --color=auto"
alias diff="diff --color=auto"
alias dir="dir --color=auto"
alias vdir="vdir --color=auto"
alias ip="ip -color"

# less destructive aliases
alias rm="rm -ri"
[[ -f /usr/bin/trash ]] && alias rm="trash "
alias mv="mv -i"
alias cp="cp -i"
alias ln="ln -i"

# common aliases
alias mkdir="mkdir -p"
alias cat="bat --style=header --style=snip --style=changes"
alias vim="nvim"
alias ls="eza -a --icons=always --color=always --group-directories-first"
alias ll="eza -al --icons=always --color=always --group-directories-first"
alias df='duf --output mountpoint,size,avail,type,filesystem'
alias du='dust -r'
alias free='free -m'
alias find='fd'
alias ping='ping -c 10'
alias h='history'
alias wget='wget --hsts-file="$XDG_DATA_HOME/wget-hsts" -c'
alias jtcl='journalctl -p 3 -xb'

# pacman aliases
alias mirror='sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist'
alias cleanup='sudo pacman -Rns $(pacman -Qtdq)'
alias fixpacman='sudo rm/var/lib/pacman/db.lck'
alias yayf="yay -Slq | fzf --multi --preview 'yay -Sii {1}' --preview-window=down:75% | xargs -ro yay -S"
[ ! -x /usr/bin/yay ] && [ -x /usr/bin/paru ] && alias yay='paru' && alias yayf='paru -Slq | fzf --multi --preview "paru -Sii {1}" --preview-window=down:75% | xargs -ro paru -S'

#######################################################
# SPECIAL FUNCTIONS
#######################################################

up() {
    if command -v topgrade &>/dev/null; then
        topgrade -k --only system
    elif command -v yay &>/dev/null; then
        yay -Syu "$@"
    else
        sudo pacman -Syu "$@"
    fi
}

upall() {
    if command -v topgrade &>/dev/null; then
        topgrade -k --no-self-update "$@"
    else
        echo "topgrade is not installed."
    fi
}

clean() {
    sudo paccache -rk1
    sudo paccache -ruk0
    cargo cache -a
}

safetouch() {
    mkdir -p "$(dirname "$1")" && touch "$1"
}

ref() {
    exec zsh
}

if command -v pkgfile &>/dev/null; then
    # shellcheck disable=SC1091
    source /usr/share/doc/pkgfile/command-not-found.zsh
fi
