#!/bin/bash
# Clean-up home directory environment variables

export GTK_RC_FILES="$XDG_CONFIG_HOME"/gtk-1.0/gtkrc
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
export ANDROID_SDK_HOME="$XDG_CONFIG_HOME/android"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export LESSHISTFILE="-"
export FFMPEG_DATADIR="$XDG_CONFIG_HOME"/ffmpeg
export GOPATH="$XDG_DATA_HOME"/go
export GOMODCACHE="$XDG_CACHE_HOME"/go/mod
export LEIN_HOME="$XDG_DATA_HOME"/lein
export DOTNET_CLI_HOME="$XDG_DATA_HOME"/dotnet
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv
export __GL_SHADER_DISK_CACHE_PATH="${XDG_CACHE_HOME}/nv"
export GNUPGHOME="${XDG_DATA_HOME}/gnupg"

# Defaults:
export EDITOR="nvim"
export VISUAL="nvim"
export PAGER="less -R"

# setup git path
export GIT_CONFIG_GLOBAL="${XDG_CONFIG_HOME:-$HOME/.config}/git/config"

if [[ ! -f "$GIT_CONFIG_GLOBAL" ]]; then
  mkdir -p "$XDG_CONFIG_HOME/git"
  touch "$GIT_CONFIG_GLOBAL"
fi

# spicetify
export PATH=$PATH:"$HOME/.spicetify"

# cargo
export PATH=$PATH:"$CARGO_HOME"/bin
export PATH=$PATH:"$RUSTUP_HOME"/bin
# go
export PATH=$PATH:"$GOPATH"/bin

export TERMINAL='/usr/bin/kitty'

#colors
export MANPAGER="sh -c 'sed -u -e \"s/\\x1B\[[0-9;]*m//g; s/.\\x08//g\" | bat -p -lman'"
export MANROFFOPT="-P -c"
export LESS='-R --use-color -Dd+r$Du+b$'
