#!/usr/bin/env bash

TMP_FILE="$XDG_RUNTIME_DIR/hyprland-show-desktop"

CURRENT_WORKSPACE=$(hyprctl monitors -j | jq '.[] | .activeWorkspace | .name' | sed 's/"//g')

# initialize accumulators to avoid accidental "unbound" behavior
CMDS=""
TMP_ADDRESS=""

if [ -s "$TMP_FILE-$CURRENT_WORKSPACE" ]; then
  # read each line from the file into ADDRESS_ARRAY
  readarray -t ADDRESS_ARRAY <"$TMP_FILE-$CURRENT_WORKSPACE"

  for address in "${ADDRESS_ARRAY[@]}"; do
    CMDS+="dispatch movetoworkspacesilent name:$CURRENT_WORKSPACE,address:$address;"
  done

  hyprctl --batch "$CMDS"

  rm "$TMP_FILE-$CURRENT_WORKSPACE"
else
  HIDDEN_WINDOWS=$(hyprctl clients -j | jq --arg CW "$CURRENT_WORKSPACE" '.[] | select (.workspace .name == $CW) | .address')

  # split the jq output into lines
  readarray -t ADDRESS_ARRAY <<<"$HIDDEN_WINDOWS"

  for address in "${ADDRESS_ARRAY[@]}"; do
    # remove double quotes using parameter expansion
    address=${address//\"/}

    # test the variable's value (quoted!)
    if [[ -n "$address" ]]; then
      TMP_ADDRESS+="${address}\n"
    fi

    CMDS+="dispatch movetoworkspacesilent special:desktop,address:${address};"
  done

  hyprctl --batch "$CMDS"

  echo -e "$TMP_ADDRESS" | sed -e '/^$/d' >"$TMP_FILE-$CURRENT_WORKSPACE"
fi
