#!/usr/bin/env bash

HYPRGAMEMODE=$(hyprctl getoption animations:enabled | awk 'NR==1{print $2}')

if [ "$HYPRGAMEMODE" = 1 ]; then
  hyprctl --batch "\
        keyword animations:enabled 0;\
        keyword animation borderangle,0; \
        keyword decoration:shadow:enabled 0;\
        keyword decoration:blur:enabled 0;\
        keyword general:gaps_in 0;\
        keyword general:gaps_out 0;\
        keyword decoration:active_opacity 1;\
        keyword decoration:inactive_opacity 1;\
        keyword general:border_size 1;\
        keyword decoration:rounding 0"

  qs -c dms ipc call bar hide
  notify-send --icon=dialog-information "Gamemode activated" "Animations and blur disabled"
  exit
else
  hyprctl reload
  qs -c dms ipc call bar reveal
  notify-send --icon=dialog-information "Gamemode deactivated" "Default settings restored"
  exit 0
fi
