#!/usr/bin/bash

switch="$1"
DISPATCH=(hyprctl dispatch exec '[float; size 75% 75% ]')
TERMINAL="kitty -e"
UPDATE_CMD="figlet -f smslant updates; update"

case "$switch" in
yazi)
  "${DISPATCH[@]}" "$TERMINAL --class yazi -e yazi"
  ;;
kitty)
  "${DISPATCH[@]}" "$TERMINAL"
  ;;
update)
  "${DISPATCH[@]}" "$TERMINAL fish -c '$UPDATE_CMD'"
  ;;

*)
  echo "Usage: $0 {yazi|kitty|update}"
  exit 1
  ;;
esac
