#!/bin/bash
apps=(
  # "waypaper --restore"
  "clipse -listen"
  "pypr"
  "/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1"
  "qs -c DankMaterialShell"
)

for app in "${apps[@]}"; do
  app2unit -- $app &
done
