#!/bin/bash

# =======================
# CORE COMPONENTS
# =======================
core_packages=(
  hyprland      # Wayland compositor
  uwsm          # Universal Wayland Session Manager
  rofi-wayland  # Wayland launcher
  app2unit-git  # Run applications as units
  hypridle      # Idle management
  hyprlock      # Lock screen
  hyprpaper     # Wallpaper daemon
  pyprland      # for scratchpads
  waybar        # Status bar
  brightnessctl # Screen brightness
  playerctl     # Media controller
  dolphin       # File manager
  kitty         # Terminal emulator

  xdg-desktop-portal-gtk      # Desktop portal for GTK apps
  xdg-desktop-portal-hyprland # Desktop portal for Hyprland
  archlinux-xdg-menu          # Arch Linux menu integration
  xdg-user-dirs               # User directories

  #required by vscode and other apps to store keyrings
  gnome-keyring
  seahorse
  libsecret

  # Sytem tools
  pacman-contrib
  bluez
  bluez-utils
  ufw
)
export core_packages

# =======================
# FONTS
# =======================
fonts=(
  powerline-fonts
  ttf-nerd-fonts-symbols
  ttf-nerd-fonts-symbols-mono
  ttf-nerd-fonts-symbols-common
  ttf-jetbrains-mono-nerd
  ttf-font-awesome
  noto-fonts-cjk
  noto-fonts-extra
)
export fonts

# =======================
# APPEARANCE / THEMING
# =======================
appearance=(
  apple_cursor
  nwg-look
  kvantum
  kvantum-qt5
  qt5-wayland
  qt6-wayland
)
export appearance

# =======================
# Input tools and utilities
# =======================
input_tools=(
  wf-recorder
  clipse-gui
  clipse
  wtype
  wmctrl
  xdotool
  libinput-gestures
  libva-intel-driver
)
export input_tools
