#!/usr/bin/env bash

core=(
  hyprland
  hyprlock
  hypridle
  hyprpicker
  hyprsunset
  hyprshot
  xdg-desktop-portal-hyprland
  uwsm
  app2unit-git
  polkit-gnome
  rofi-wayland
  grimblast
  waypaper
  swww
  imv
  matugen-bin
  ags-hyprpanel-git #TODO: replace with quickshell
  pyprland
  devify
  brightnessctl
  playerctl
  nautilus
  sddm-git
  kitty
  rofimoji
  yad # for keybinds popup to work
  xdg-desktop-portal-gtk
  xdg-user-dirs
  xdg-autostart
  xdg-terminal-exec
  gnome-keyring
  libgnome-keyring
  topgrade
  mission-center
  udiskie
  ntfs-3g
  exfatprogs
  dosfstools
  f2fs-tools
  gparted
  gpart
  overskride
  ufw
  pwvucontrol
  networkmanager
  usbutils
  man-db
  xorg-xhost
  layer-shell-qt
  layer-shell-qt5
  qt6-multimedia-ffmpeg
  libfido2
  clipse
  clipse-gui
  wmctrl
  nvtop
  btop
  reflector
  pacman-contrib
)

fonts=(
  ttf-nerd-fonts-symbols
  ttf-nerd-fonts-symbols-mono
  ttf-apple-emoji
  apple-fonts
  ttf-font-awesome
  noto-fonts-cjk
  noto-fonts-extra
  ttf-liberation
)

theming=(
  apple_cursor
  nwg-look
  kvantum
  kvantum-qt5
  qt6ct-kde
  qt5ct-kde

)

optional=(
  brave-bin
  visual-studio-code-bin
  qbittorrent
  mpv
  neovim
  spotify-launcher
  git-delta
  localsend
  antidot
  vesktop-bin
  yazi
)

drivers=(
  mesa-utils
  wireless-regdb
  libva-utils
  vulkan-tools
  vulkan-headers
)

kernel_version=$(uname -r)
if [[ "$kernel_version" == *"-zen"* ]]; then
  drivers+=(
    linux-zen-headers
  )
elif [[ "$kernel_version" == *"-lts"* ]]; then
  drivers+=(
    linux-lts-headers
  )
elif [[ "$kernel_version" == *"-cachyos"* ]]; then
  drivers+=(
    linux-cachyos-headers
  )
else
  drivers+=(
    linux-headers
  )
fi

gpu_info=$(lspci -nn | grep -Ei "VGA compatible controller|3D controller|Display controller")

# NVIDIA
if [[ $gpu_info == *"NVIDIA Corporation"* ]]; then
  drivers+=(
    libva-nvidia-driver
    nvidia-utils
    nvidia-dkms
    nvidia-settings
    nvidia-prime
    opencl-nvidia
  )
fi

# AMD/ATI
if [[ $gpu_info == *"AMD/ATI"* ]]; then
  drivers+=(
    xf86-video-amdgpu
    vulkan-radeon
    libva-mesa-driver
  )
fi

# Intel
if [[ $gpu_info == *"Intel Corporation"* ]]; then
  drivers+=(
    libva-intel-driver
    intel-media-driver
    vulkan-intel
  )
fi

if [[ ! $gpu_info =~ (NVIDIA|AMD/ATI|Intel Corporation) ]]; then
  print_warning "No supported GPU found, skipping GPU-specific driver installation."
fi

export optional
export drivers
export core
export fonts
export theming
