
[".local/share/fonts/maple-mono"]
  url     = {{ gitHubLatestReleaseAssetURL "subframe7536/maple-font" "MapleMonoNormal-TTF-AutoHint.zip" | quote }}
  type    = "archive"
  include = ["*.ttf"]
  refreshPeriod = "336h"

[".local/share/icons/macOS"]
  url     = {{ gitHubLatestReleaseAssetURL "driedpampas/macOS-hyprcursor" "macOS.Hyprcursor.SVG.White.tar.gz" | quote }}
  type = "archive"
  refreshPeriod = "744h"

["Pictures/Wallpapers"]
  type    = "archive"
  url     = {{ gitHubLatestReleaseAssetURL "vantesh/wallpapers" "wallpapers.zip" | quote }}
  refreshPeriod = "168h"


