#!/bin/bash

theme="$HOME/.config/rofi/scripts/screenshot/style.rasi"
XDG_PICTURES_DIR="${XDG_PICTURES_DIR:-$HOME/Pictures}"

if ! pgrep -x "gpu-screen-reco" >/dev/null; then
  option3=""
else
  option3=""
fi

option0="󰆞" # Area
option1="" # Fullscreen
option2="󰔟" # Countdown (3s) fullscreen
option4="" # Open Folder

options="$option0\n$option1\n$option2\n$option3\n$option4"
selected="$(echo -e "$options" | rofi -dmenu -mesg "Screenshot" -theme ${theme})"

case $selected in
"$option0")
  # Small delay to avoid capturing the rofi window
  sleep 0.5
  if hyprshot -zsm region --clipboard-only; then
    notify-send "Hyprshot" "Screenshot copied to clipboard!" -i ~/.config/rofi/images/screenshot.svg
  fi
  ;;
"$option1")
  sleep 0.5
  hyprshot -zm output
  ;;
"$option2")
  # Countdown 3 seconds, then take a fullscreen screenshot
  notify-send "Taking screenshot in 5 seconds..." -i ~/.config/rofi/images/screenshot.svg -t 3500 -u low
  sleep 3
  hyprshot -zm output
  ;;
"$option3")
  # If gpu-screen-recorder is not running, start recording, else stop recording.
  if ! pgrep -x "gpu-screen-reco" >/dev/null; then
    ~/.config/hypr/hyprland/scripts/screenrecord
  else
    killall -SIGINT gpu-screen-recorder
    notify-send "Recording stopped" "Video saved in $XDG_PICTURES_DIR/ScreenRecordings" -i ~/.config/rofi/images/movie.svg
  fi
  ;;
"$option4")
  xdg-open "$XDG_PICTURES_DIR"/Screenshots
  ;;
esac
