#!/usr/bin/env bash

# Exit if wpaperd isn't running
if ! pgrep -x wpaperd >/dev/null; then
    notify-send "wpaperd not running!" --urgency=critical
    exit 1
fi

# Get all monitor names
monitors=$(hyprctl monitors -j | jq -r '.[].name')

# Loop through monitors and advance wallpaper
for monitor in $monitors; do
    wpaperctl next-wallpaper "$monitor"
    current=$(wpaperctl get-wallpaper "$monitor" | head -n1)
    notify-send "Wallpaper changed" -i "$current" --app-name=Wallpaper
done
