[mgr]
  cwd = { fg = "#bfc6dc", bold = true }

  hovered         = { fg = "#d8e2ff", bg = "#2b4678" }
  preview_hovered = { underline = true, bold = true }

  find_keyword  = { fg = "#bfc6dc", italic = true }
  find_position = { fg = "#debcdf", bg = "reset", italic = true }


  border_symbol = "│"
  border_style  = { fg = "#aec6ff" }

  syntect_theme = "~/.config/yazi/theme/catppuccin-mocha.tmTheme"

[mode]
  normal_main = { fg = "#112f60", bg = "#aec6ff", bold = true }
  normal_alt  = { fg = "#2b4678", bg = "#e2e2e9" }

  select_main = { fg = "#293041", bg = "#bfc6dc", bold = true }
  select_alt  = { fg = "#3f4759", bg = "#e2e2e9" }

  unset_main = { fg = "#402843", bg = "#debcdf", bold = true }
  unset_alt  = { fg = "#583e5b", bg = "#e2e2e9" }

[status]
  separator_open  = ""
  separator_close = ""

  perm_type  = { fg = "#aec6ff" }
  perm_read  = { fg = "#d5c871" }
  perm_write = { fg = "#abc7ff" }
  perm_exec  = { fg = "#fbb0d8" }
  perm_sep   = { fg = "#e2e2e9" }

[which]
  mask            = { bg = "#1e1f25" }
  cand            = { fg = "#aec6ff" }
  rest            = { bg = "#1e1f25" }
  desc            = { fg = "#bfc6dc" }
  separator       = "  "
  separator_style = { fg = "#debcdf" }

[notify]
  title_info  = { fg = "#91d5ad" }
  title_warn  = { fg = "#d5c871" }
  title_error = { fg = "#ffb4ab" }

[filetype]
  rules = [
    # Images
    { mime = "image/*", fg = "#bfc6dc" },

    # Videos
    { mime = "video/*", fg = "#debcdf" },
    { mime = "audio/*", fg = "#debcdf" },

    # Archives
    { mime = "application/zip", fg = "#ffb4ab" },
    { mime = "application/gzip", fg = "#ffb4ab" },
    { mime = "application/x-tar", fg = "#ffb4ab" },
    { mime = "application/x-bzip", fg = "#ffb4ab" },
    { mime = "application/x-bzip2", fg = "#ffb4ab" },
    { mime = "application/x-7z-compressed", fg = "#ffb4ab" },
    { mime = "application/x-rar", fg = "#ffb4ab" },

    # Fallback
    { name = "*", fg = "#aec6ff", bold = true },
    { name = "*/", fg = "#bfc6dc", bold = true },
  ]
[[plugin.prepend_fetchers]]
  id   = "git"
  name = "*"
  run  = "git"

[[plugin.prepend_fetchers]]
  id   = "git"
  name = "*/"
  run  = "git"
