
[config]
  mode        = "dark"
  reload_apps = true

[templates.hyprland]
  input_path  = '~/.config/matugen/templates/hyprland.template'
  output_path = '~/.config/hypr/hyprland/theme/colors.conf'

[templates.btop]
  input_path  = '~/.config/matugen/templates/btop.template'
  output_path = '~/.config/btop/themes/matugen.theme'

[templates.bat]
  input_path  = '~/.config/matugen/templates/bat.template'
  output_path = '~/.config/bat/themes/Matugen.tmTheme'
  post_hook   = 'bat cache --build &> /dev/null'

[templates.kitty]
  input_path  = '~/.config/matugen/templates/kitty.template'
  output_path = '~/.config/kitty/themes/Matugen.conf'
  post_hook   = 'kitty +kitten themes --reload-in=all Matugen'

[templates.yazi]
  input_path  = '~/.config/matugen/templates/yazi.template'
  output_path = '~/.config/yazi/theme.toml'


[templates.neovim]
  input_path  = '~/.config/matugen/templates/neovim.template'
  output_path = '~/.config/nvim/lua/plugins/colorscheme.lua'

[templates.rofi]
  input_path  = '~/.config/matugen/templates/rofi.template'
  output_path = '~/.config/rofi/colors.rasi'

[templates.qt5ct]
  input_path  = '~/.config/matugen/templates/qtct.template'
  output_path = '~/.config/qt5ct/colors/Matugen.conf'

[templates.qt6ct]
  input_path  = '~/.config/matugen/templates/qtct.template'
  output_path = '~/.config/qt6ct/colors/Matugen.conf'

[templates.fzf]
  input_path  = '~/.config/matugen/templates/fzf.template'
  output_path = '~/.config/zsh/fzf'

[templates.kvantum]
  input_path  = '~/.config/matugen/templates/kvantum/kvantum.template'
  output_path = '~/.config/Kvantum/Matugen/Matugen.kvconfig'

[templates.kvantum-svg]
  input_path  = "~/.config/matugen/templates/kvantum/kvantum.svg"
  output_path = "~/.config/Kvantum/Matugen/Matugen.svg"

[templates.gtk4]
  input_path  = '~/.config/matugen/templates/gtk/gtk4.template'
  output_path = '~/.config/gtk-4.0/colors.css'

[templates.gtk3]
  input_path  = '~/.config/matugen/templates/gtk/gtk3.template'
  output_path = '~/.config/gtk-3.0/colors.css'
  post_hook   = '~/.config/matugen/scripts/gtk-fix'

[templates.folder]
  input_path  = '~/.config/matugen/templates/folder-color.template'
  output_path = '~/.config/matugen/papirus-folders/folder-color.txt'
  post_hook   = '~/.config/matugen/scripts/folder-colors'

[templates.spicetify]
  input_path  = '~/.config/matugen/templates/spotify.template'
  output_path = '~/.config/spicetify/Themes/marketplace/color.ini'
  post_hook   = '~/.config/matugen/scripts/spotify-reload'

[templates.vscode]
  input_path  = "~/.config/matugen/templates/vscode.template"
  output_path = "~/.vscode/extensions/hyprluna.hyprluna-theme-1.0.2/themes/hyprluna.json"


[config.custom_colors]
  red    = "#f38ba8"
  green  = "#a6e3a1"
  yellow = "#f9e2af"
  blue   = "#89b4fa"
  orange = "#fab387"
  purple = "#cba6f7"
