#!/usr/bin/env bash

current_theme=$(spicetify config current_theme)

if [[ -z "$current_theme" || "$current_theme" != "marketplace" ]]; then
  spicetify config current_theme marketplace
fi

# only apply if spotify is running
if pgrep -x "spotify" >/dev/null; then
  spicetify apply &>/dev/null
fi
