#!/bin/bash
user_services=(
  hyprpolkitagent.service
  gnome-keyring-daemon.service
  hypridle.service
  hyprpaper.service
)
system_services=(
  bluetooth.service
  paccache.timer
  sddm.service
  ufw.service
)

for service in "${user_services[@]}"; do
  enable_service "$service" "user"
done
for service in "${system_services[@]}"; do
  enable_service "$service" "system"
done

# enable ufw firewall
sudo ufw enable || fail "Failed to enable UFW firewall."

# setup Dns over Https using dnscrypt-proxy
if confirm "Setup DNS over HTTPS using dnscrypt-proxy?"; then
  printc cyan "Setting up DNS over HTTPS..."

  if ! has_cmd dnscrypt-proxy; then
    install_package "dnscrypt-proxy" || fail "Failed to install dnscrypt-proxy."

  fi

  sudo rm -f /etc/resolv.conf || fail "Failed to remove existing resolv.conf."
  sudo tee /etc/resolv.conf >/dev/null <<EOF
#Generated by dnscrypt-proxy
nameserver ::1
nameserver 127.0.0.1
options edns0
EOF
  printc cyan "Making /etc/resolv.conf immutable..."
  sudo chattr +i /etc/resolv.conf || fail "Failed to make resolv.conf immutable."
  enable_service "dnscrypt-proxy.service" "system"

  CONFIG_FILE="/etc/dnscrypt-proxy/dnscrypt-proxy.toml"
  declare -A config_values=(
    ["server_names"]="['cloudflare', 'cloudflare-ipv6']"
  )

  printc cyan "Updating $CONFIG_FILE with DNS settings..."
  for key in "${!config_values[@]}"; do
    update_config "$CONFIG_FILE" "$key" "${config_values[$key]}"
  done

  # disable systemd-resolved being started by networkmanager
  SYM_CONF="/etc/NetworkManager/conf.d/no-systemd-resolved.conf"
  if [[ ! -f "$SYM_CONF" ]]; then
    sudo tee "$SYM_CONF" >/dev/null <<EOF
[main]
systemd-resolved=false
EOF
    printc green "Created $SYM_CONF to disable systemd-resolved."
  else
    printc yellow "$SYM_CONF already exists, skipping creation."
  fi

  # disable systemd-resolved service
  if sudo systemctl is-active --quiet systemd-resolved; then
    sudo systemctl stop systemd-resolved || fail "Failed to stop systemd-resolved."
    sudo systemctl disable systemd-resolved || fail "Failed to disable systemd-resolved."
    printc green "systemd-resolved service stopped and disabled."

    # Restart NetworkManager to apply changes
    sudo systemctl restart NetworkManager || fail "Failed to restart NetworkManager."

  else
    printc yellow "systemd-resolved service is not active, skipping stop/disable."
  fi

else
  printc yellow "Skipping DNS over HTTPS setup."
fi
