#!/bin/bash

# =============================================================================
# CONFIGURATION ARRAYS
# =============================================================================

readonly USER_SERVICES=(
  hyprpolkitagent.service
  gnome-keyring-daemon.service
  hypridle.service
)

readonly SYSTEM_SERVICES=(
  bluetooth.service
  paccache.timer
  sddm.service
  ufw.service
)

readonly DNSCRYPT_CONFIG_FILE="/etc/dnscrypt-proxy/dnscrypt-proxy.toml"
readonly NETWORKMANAGER_CONF="/etc/NetworkManager/conf.d/no-systemd-resolved.conf"

# =============================================================================
# SERVICE MANAGEMENT FUNCTIONS
# =============================================================================

enable_user_services() {
  for service in "${USER_SERVICES[@]}"; do
    enable_service "$service" "user"
  done
}

enable_system_services() {
  for service in "${SYSTEM_SERVICES[@]}"; do
    enable_service "$service" "system"
  done
}

enable_ufw_firewall() {
  printc -n cyan "Enabling UFW firewall... "
  if sudo ufw enable >/dev/null 2>&1; then
    printc green "OK"
  else
    fail "FAILED"
  fi
}

# =============================================================================
# DNS CONFIGURATION FUNCTIONS
# =============================================================================

install_dnscrypt_proxy() {
  if ! has_cmd dnscrypt-proxy; then
    printc cyan "Installing dnscrypt-proxy..."
    install_package "dnscrypt-proxy" || fail "Failed to install dnscrypt-proxy."
  else
    printc yellow "dnscrypt-proxy is already installed."
  fi
}

configure_resolv_conf() {
  printc -n cyan "Configuring resolv.conf... "
  if sudo rm -f /etc/resolv.conf && sudo tee /etc/resolv.conf >/dev/null <<EOF && sudo chattr +i /etc/resolv.conf; then
#Generated by dnscrypt-proxy
nameserver ::1
nameserver 127.0.0.1
options edns0
EOF
    printc green "OK"
  else
    fail "FAILED"
  fi
}

configure_dnscrypt_proxy() {
  printc -n cyan "Configuring dnscrypt-proxy... "
  declare -A config_values=(
    ["server_names"]="['cloudflare', 'cloudflare-ipv6']"
  )

  printc cyan "Updating $DNSCRYPT_CONFIG_FILE with DNS settings..."
  for key in "${!config_values[@]}"; do
    update_config "$DNSCRYPT_CONFIG_FILE" "$key" "${config_values[$key]}"
  done

  enable_service "dnscrypt-proxy.service" "system"
  printc green "OK"
}

disable_systemd_resolved() {
  printc -n cyan "Disabling systemd-resolved... "

  # Create NetworkManager configuration
  if [[ ! -f "$NETWORKMANAGER_CONF" ]]; then
    sudo tee "$NETWORKMANAGER_CONF" >/dev/null <<EOF
[main]
systemd-resolved=false
EOF
  fi

  # Stop and disable systemd-resolved service
  if sudo systemctl is-active --quiet systemd-resolved; then
    sudo systemctl stop systemd-resolved >/dev/null 2>&1
    sudo systemctl disable systemd-resolved >/dev/null 2>&1
    sudo systemctl restart NetworkManager >/dev/null 2>&1
  fi

  printc green "OK"
}

setup_dns_over_https() {
  printc cyan "Setting up DNS over HTTPS..."

  install_dnscrypt_proxy
  configure_resolv_conf
  configure_dnscrypt_proxy
  disable_systemd_resolved

  printc green "DNS over HTTPS setup completed successfully."
}

# =============================================================================
# MAIN EXECUTION FUNCTIONS
# =============================================================================

main() {
  enable_user_services
  enable_system_services
  enable_ufw_firewall

  if confirm "Setup DNS over HTTPS using dnscrypt-proxy?"; then
    setup_dns_over_https
  else
    printc yellow "Skipping DNS over HTTPS setup."
  fi
}

main
