#!/bin/bash

# =============================================================================
# CONFIGURATION ARRAYS
# =============================================================================

readonly USER_SERVICES=(
  hyprpolkitagent.service
  gnome-keyring-daemon.service
  hypridle.service
)

readonly SYSTEM_SERVICES=(
  bluetooth.service
  sddm.service
  ufw.service
)

readonly DNSCRYPT_CONFIG_FILE="/etc/dnscrypt-proxy/dnscrypt-proxy.toml"
readonly NETWORKMANAGER_CONF="/etc/NetworkManager/conf.d/no-systemd-resolved.conf"

# =============================================================================
# SERVICE MANAGEMENT FUNCTIONS
# =============================================================================

enable_user_services() {
  for service in "${USER_SERVICES[@]}"; do
    enable_service "$service" "user"
  done
}

enable_system_services() {
  for service in "${SYSTEM_SERVICES[@]}"; do
    enable_service "$service" "system"
  done
}

enable_ufw_firewall() {
  printc -n cyan "Enabling UFW firewall... "
  if sudo ufw enable >/dev/null 2>&1; then
    printc green "OK"
  else
    fail "FAILED"
  fi
}

services_to_disable=(
  NetworkManager-wait-online.service
)
for service in "${services_to_disable[@]}"; do
  disable_service "$service" "system"
done

# =============================================================================
# SDDM CONFIGURATION
# =============================================================================

configure_sddm() {
  printc -n cyan "Configuring SDDM... "
  write_system_config "/etc/sddm.conf.d/10-wayland.conf" "SDDM Wayland configuration" <<'EOF'
[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell
EOF

  write_system_config "/etc/sddm.conf.d/hidpi.conf" "SDDM HIDPI configuration" <<'EOF'
[Wayland]
EnableHiDPI=true
EOF
  printc green "OK"
}

# =============================================================================
# DNS CONFIGURATION FUNCTIONS
# =============================================================================

install_dnscrypt_proxy() {
  if ! has_cmd dnscrypt-proxy; then
    printc -n cyan "Installing dnscrypt-proxy... "
    install_package "dnscrypt-proxy" || fail "FAILED"
    printc green "OK"
  else
    printc yellow "Exists"
  fi
}

configure_resolv_conf() {
  printc -n cyan "Configuring resolv.conf... "

  if sudo rm -f /etc/resolv.conf; then
    if write_system_config "/etc/resolv.conf" "DNS configuration" <<'EOF'; then
# Generated by dnscrypt-proxy
nameserver ::1
nameserver 127.0.0.1
options edns0
EOF
      if sudo chattr +i /etc/resolv.conf; then
        printc green "OK"
      else
        fail "FAILED to set immutable attribute"
      fi
    else
      fail "FAILED to write resolv.conf"
    fi
  else
    fail "FAILED to remove existing resolv.conf"
  fi
}

configure_dnscrypt_proxy() {
  printc -n cyan "Configuring dnscrypt-proxy... "
  declare -A config_values=(
    ["server_names"]="['cloudflare', 'cloudflare-ipv6']"
  )
  for key in "${!config_values[@]}"; do
    update_config "$DNSCRYPT_CONFIG_FILE" "$key" "${config_values[$key]}"
  done
  printc green "OK"
  enable_service "dnscrypt-proxy.service" "system"

}

disable_systemd_resolved() {

  # Create NetworkManager configuration
  if [[ ! -f "$NETWORKMANAGER_CONF" ]]; then
    write_system_config "$NETWORKMANAGER_CONF" "NetworkManager configuration to disable systemd-resolved" <<'EOF'
[main]
systemd-resolved=false
EOF
  fi
  printc -n cyan "Disabling systemd-resolved... "
  # Stop and disable systemd-resolved service
  if disable_service "systemd-resolved.service" "system"; then
    printc -n cyan "Restarting NetworkManager... "
    if sudo systemctl restart NetworkManager; then
      printc green "OK"
    else
      fail "FAILED to restart NetworkManager"
    fi
  fi
}

setup_dns_over_https() {
  install_dnscrypt_proxy
  configure_resolv_conf
  configure_dnscrypt_proxy
  disable_systemd_resolved
  printc green "DNS over HTTPS setup completed successfully."
}

# =============================================================================
# PLYMOUTH CONFIGURATION FUNCTIONS
# =============================================================================

setup_plymouth() {
  printc cyan "Setting up Plymouth..."

  install_package "plymouth"

  printc -n cyan "Configuring Plymouth hooks... "
  local mkinitcpio_conf="/etc/mkinitcpio.conf"
  if ! grep -q "plymouth" "$mkinitcpio_conf"; then
    if sudo sed -i '/^HOOKS=/ s/\(.*\) filesystems\(.*\)/\1 plymouth filesystems\2/' "$mkinitcpio_conf"; then
      printc green "OK"
    else
      printc red "FAILED"
      return 1
    fi
  else
    printc yellow "already configured"
  fi

  # Add quiet flags to /etc/kernel/cmdline if not present
  local cmdline_file="/etc/kernel/cmdline"
  local quiet_flags="quiet loglevel=3 splash vt.global_cursor_default=0 nowatchdog"
  printc -n cyan "Adding quiet flags to $cmdline_file... "
  if ! grep -qw "quiet" "$cmdline_file"; then
    local existing_params
    existing_params=$(cat "$cmdline_file" 2>/dev/null || echo "")
    local combined_params="$existing_params $quiet_flags"
    combined_params=$(echo "$combined_params" | sed 's/[ ]\+/ /g' | sed 's/^ *//' | sed 's/ *$//')
    echo "$combined_params" | sudo tee "$cmdline_file" >/dev/null
    printc green "OK"
  else
    printc yellow "already present"
  fi

  regenerate_initramfs || return 1
}

# =============================================================================
# MAIN EXECUTION FUNCTIONS
# =============================================================================

main() {
  if confirm "Install and configure Plymouth for boot splash?"; then
    setup_plymouth
  else
    printc yellow "Skipping Plymouth setup."
  fi
  enable_user_services
  enable_system_services
  enable_ufw_firewall
  configure_sddm
  echo
  if confirm "Setup DNS over HTTPS using dnscrypt-proxy?"; then
    setup_dns_over_https
  else
    printc yellow "Skipping DNS over HTTPS setup."
  fi

}

main
