[config]


[templates.fish]
  input_path  = '~/.config/matugen/templates/terminal/colors.fish'
  output_path = '~/.config/fish/themes/Matugen.theme'
  post_hook   = '~/.config/matugen/scripts/update_terminal.sh &'

[templates.atuin]
  input_path  = "~/.config/matugen/templates/terminal/atuin.toml"
  output_path = "~/.config/atuin/themes/matugen.toml"


[templates.spotify]
  input_path  = '~/.config/matugen/templates/spotify.ini'
  output_path = '~/.config/spicetify/Themes/Sleek/color.ini'
  post_hook   = '~/.config/matugen/scripts/update_spotify.sh &'
