# Matugen Configuration for Rofi with swww integration

[config]
  reload_apps = true
  mode        = "dark"

[config.reload_apps_list]
  gtk_theme = true


[config.wallpaper]
  command = "swww"
  arguments = [
    "img",
    "--transition-type",
    "grow",
    "--transition-fps",
    "120",
    "--transition-step",
    "100",
    "--transition-duration",
    "1.5",
  ]
  set = true

[templates.hyprland]
  input_path  = '~/.config/matugen/templates/hyprland.template'
  output_path = '~/.config/hypr/hyprland/theme/colors.conf'

[templates.btop]
  input_path  = '~/.config/matugen/templates/btop.template'
  output_path = '~/.config/btop/themes/matugen.theme'

[templates.bat]
  input_path  = '~/.config/matugen/templates/bat.template'
  output_path = '~/.config/bat/themes/Matugen.tmTheme'
  post_hook   = 'bat cache --build &> /dev/null'

[templates.kitty]
  input_path  = '~/.config/matugen/templates/kitty.template'
  output_path = '~/.config/kitty/themes/colors-matugen.conf'
  post_hook   = 'kitty +kitten themes --reload-in=all Colors-Matugen'

[templates.yazi]
  input_path  = '~/.config/matugen/templates/yazi.template'
  output_path = '~/.config/yazi/theme.toml'

[templates.gtk3]
  input_path  = '~/.config/matugen/templates/gtk.template'
  output_path = '~/.config/gtk-3.0/colors.css'
  post_hook   = 'systemctl --user restart hyprpolkitagent'

[templates.gtk4]
  input_path  = '~/.config/matugen/templates/gtk.template'
  output_path = '~/.config/gtk-4.0/colors.css'
  post_hook   = 'systemctl --user restart xdg-desktop-portal-gtk'

[templates.neovim]
  input_path  = '~/.config/matugen/templates/neovim.template'
  output_path = '~/.config/nvim/lua/plugins/colorscheme.lua'

[templates.rofi]
  input_path  = '~/.config/matugen/templates/rofi.template'
  output_path = '~/.config/rofi/colors.rasi'

  # [templates.starship]
  #   input_path  = '~/.config/matugen/templates/starship.template'
  #   output_path = '~/.config/starship/starship.toml'

[templates.qt5ct]
  input_path  = '~/.config/matugen/templates/qtct.template'
  output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
  input_path  = '~/.config/matugen/templates/qtct.template'
  output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.color-scheme]
  input_path  = '~/.config/matugen/templates/qt-colors.template'
  output_path = '~/.local/share/color-schemes/Matugen.colors'

[templates.fzf]
  input_path  = '~/.config/matugen/templates/fzf.template'
  output_path = '~/.config/zsh/fzf'


[templates.vscode]
  input_path  = "~/.config/matugen/templates/vscode.template"
  output_path = "~/.vscode/extensions/hyprluna.hyprluna-theme-1.0.2/themes/hyprluna.json"


[config.custom_colors]
  red    = "#f38ba8"
  green  = "#a6e3a1"
  yellow = "#f9e2af"
  blue   = "#89b4fa"
  orange = "#fab387"
  purple = "#cba6f7"
