#!/usr/bin/env bash

services=(
  "hyprpolkitagent"
  "xdg-desktop-portal-gtk"
)

for service in "${services[@]}"; do
  if systemctl is-active --quiet "$service"; then
    systemctl restart "$service"
  fi
done

GTK_CSS=~/.config/gtk-4.0/gtk.css
GTK_DARK_CSS=~/.config/gtk-4.0/gtk-dark.css
IMPORT_LINE='@import "colors.css";'

if [[ -f $GTK_CSS && -f $GTK_DARK_CSS ]] &&
  grep -Fxq "$IMPORT_LINE" "$GTK_CSS" &&
  grep -Fxq "$IMPORT_LINE" "$GTK_DARK_CSS"; then
  :
else
  rm -f "$GTK_CSS" "$GTK_DARK_CSS"
  echo "$IMPORT_LINE" >"$GTK_CSS"
  echo "$IMPORT_LINE" >"$GTK_DARK_CSS"
fi
