#!/usr/bin/env bash

theme="$HOME/.config/rofi/style.rasi"
screenrecord_script="$HOME/.config/scripts/rofi/screenrecord"
XDG_PICTURES_DIR="${XDG_PICTURES_DIR:-$HOME/Pictures}"

if ! pgrep -x "gpu-screen-reco" >/dev/null; then
  record=""
else
  record=""
fi

area="󰆞"
fullscreen=""
countdown="󰔟"
folder=""

options="$fullscreen\n$area\n$countdown\n$record\n$folder"
selected="$(echo -e "$options" | rofi -dmenu -mesg "Screenshot" -theme ${theme})"

case $selected in
"$area")
  # Small delay to avoid capturing the rofi window
  sleep 0.5
  hyprshot -zm region --clipboard-only

  ;;
"$fullscreen")
  sleep 0.5
  hyprshot -zm output
  ;;
"$countdown")
  # Countdown 3 seconds, then take a fullscreen screenshot
  notify-send "Taking screenshot in 5 seconds..." -i camera -t 3500 -u low
  sleep 3
  hyprshot -zm output
  ;;
"$record")
  # If gpu-screen-recorder is not running, start recording, else stop recording.
  if ! pgrep -x "gpu-screen-reco" >/dev/null; then
    "$screenrecord_script"
  else
    killall -SIGINT gpu-screen-recorder
    notify-send "Recording stopped" "Video saved in $XDG_PICTURES_DIR/ScreenRecordings" -i video
  fi
  ;;
"$folder")
  xdg-open "$XDG_PICTURES_DIR"/Screenshots
  ;;
esac
