[plugins]
enabled = [
  "yuuto/arch-updater",
  "kenn/keybind-cheatsheet",
  "noctalia/screen_recorder",
  "noctalia/notes",
]

[plugin_settings."kenn/keybind-cheatsheet"]
cheatsheet_layer = "overlay"

[plugin_settings."yuuto/arch-updater"]
panel_placement = "floating"
terminal = 'xdg-terminal-exec --title="System Update"'
update_cmd = "~/.config/hypr/scripts/updater.sh"
auto_check_hours = 3
