[theme.templates.user.zed]
input_path = "$XDG_CONFIG_HOME/noctalia/templates/zed.json"
output_path = "$XDG_CONFIG_HOME/zed/themes/noctalia.json"

[theme.templates.user.fish]
input_path = "$XDG_CONFIG_HOME/noctalia/templates/fish.theme"
output_path = "$XDG_CONFIG_HOME/fish/themes/Noctalia.theme"
post_hook = "fish -c 'yes | fish_config theme save Noctalia'"

[theme.templates.user.atuin]
input_path = "$XDG_CONFIG_HOME/noctalia/templates/atuin.toml"
output_path = "$XDG_CONFIG_HOME/atuin/themes/noctalia.toml"

[theme.templates.user.television]
input_path = "$XDG_CONFIG_HOME/noctalia/templates/television.toml"
output_path = "$XDG_CONFIG_HOME/television/themes/noctalia.toml"

[theme.templates.user.spotify]
input_path = "$XDG_CONFIG_HOME/noctalia/templates/spotify.ini"
output_path = "$XDG_CONFIG_HOME/spicetify/Themes/Sleek/color.ini"
post_hook = 'bash "{{ config_dir }}/scripts/update_spotify.sh"'
hook_async = false

[theme.templates.user.tela]
input_path = "$XDG_CONFIG_HOME/noctalia/templates/folder-color"
output_path = "$XDG_CACHE_HOME/noctalia/folder-color.txt"
compare_to = "{{ colors.primary.default.hex }}"
colors_to_compare = [
    { name = "nord", color = "#4d576a" },
    { name = "grey", color = "#bdbdbd" },
    { name = "purple", color = "#7e57c2" },
    { name = "brown", color = "#795548" },
    { name = "dark", color = "#5294e2" },
    { name = "red", color = "#ef5350" },
    { name = "manjaro", color = "#16a085" },
    { name = "orange", color = "#e18908" },
    { name = "blue", color = "#5677fc" },
    { name = "pink", color = "#f06292" },
    { name = "ubuntu", color = "#fb8441" },
    { name = "green", color = "#66bb6a" },
    { name = "dracula", color = "#44475a" },
    { name = "yellow", color = "#ffca28" },
    { name = "black", color = "#4d4d4d" },
]
post_hook = 'bash "{{ config_dir }}/scripts/update_folders.sh" "{{ closest_color }}" "{{ mode }}"'
hook_async = false

[theme.templates.user.nvim-dark]
input_path = "$XDG_CONFIG_HOME/noctalia/templates/base46-dark.lua"
output_path = "$XDG_CACHE_HOME/wal/base46-dark.lua"

[theme.templates.user.nvim-light]
input_path = "$XDG_CONFIG_HOME/noctalia/templates/base46-light.lua"
output_path = "$XDG_CACHE_HOME/wal/base46-light.lua"

[theme.templates.user.nvim-mode]
input_path = "$XDG_CONFIG_HOME/noctalia/templates/nvim-background"
output_path = "$XDG_CACHE_HOME/wal/colors"
index = 1
