[widget.active_window]
title_scroll = "on_hover"
icon_size = 16

[widget.bluetooth]
hide_when_adapter_off = true
hide_when_no_connected_device = true

[widget.media]
hide_when_no_media = true
rotate_album_art = true
title_scroll = "on_hover"
artist_first = true
art_size = 20

[widget.network]
show_label = false

[widget.notifications]
hide_when_no_unread = true

[widget.privacy]
hide_inactive = true

[widget.taskbar]
group_by_workspace = true
hide_empty_workspaces = true
only_active_workspace = true

[widget.tray]
match_adjacent_spacing = true

[widget.widget]
type = "yuuto/arch-updater:widget"
hide_on_empty = true
glyph = "pacman"

[widget.workspaces]
font_scale = 1.25
font_weight = 600
active_pill_size = 2.5
inactive_pill_size = 1.5
focused_output_only = true
hide_when_empty = true
occupied_color = "outline"

[widget.weather]
show_condition = false